---
# tasks file for docker

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - docker

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - docker

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - docker

- name: Ensure docker is started and enabled on boot
  become: yes
  service:
    name: "{{ docker_service_name }}"
    state: started
    enabled: yes
  tags:
    - docker
