---
# tasks file for docker (Ubuntu specific)

- name: Add Docker APT repository key
  apt_key: >
    keyserver=keyserver.ubuntu.com
    id=36A1D7869245C8950F966E92D8576A8BA88D21E9
    state=present
  tags: docker

- name: Add Docker APT repository
  apt_repository: >
    repo='deb https://get.docker.com/ubuntu docker main'
    state=present
  tags: docker

- name: Install Docker packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: docker_packages
  tags: docker
